[package]
name = "yaml2nix"
version = "0.1.0"
authors = ["Euan Kemp <euank@euank.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
yaml_serde = "0.10"
serde-nix = { git = "https://github.com/euank/serde-nix.git", rev = "1e3d04d88dcbec91d0aec050a4a53cd5e8c5e2d4" }
rnix = "0.8.0"
nixpkgs-fmt = "1.3.0"

#[patch.crates-io]
## crossbeam-epoch = ">=0.9.20"
#crossbeam-epoch = { git = "https://github.com/crossbeam-rs/crossbeam", tag = "crossbeam-epoch-0.9.20" }

#[replace]
#"crossbeam-epoch:0.9.18" = { git = "https://github.com/crossbeam-rs/crossbeam", tag = "crossbeam-epoch-0.9.20" }
